# Generated by Django 4.0.3 on 2022-04-07 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='district',
            field=models.ForeignKey(db_column='id_district', on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='basic.district'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.ForeignKey(db_column='id_marital_status', on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='basic.maritalstatus'),
        ),
    ]
